### PR TITLE
Add Qwen2 to the QEfficient Transformers

### PR DESCRIPTION
**Pull request by vbaddi**
- Add support for Qwen2 Models to the QEff.
- Expected Transformers to be above 4.37+
- Model Card tested: `Qwen/Qwen1.5-4B-Chat`
- `TODO; add test cases`

### CODE REVIEW

**Comment by anujgupt-github** [comment]
Title says qwen2, but the support we are bringing is 1.5?

**Comment by vbaddi** [comment]
> Title says qwen2, but the support we are bringing is 1.5?

Yes, should work fine. do you have exact `model_card` name? can add it to test pipeline

**Comment by anujgupt-github** [comment]
Is this ready to merge?

**Comment by vbaddi** [comment]
duplicate #33

**Pull request closed without merging**
