### PR TITLE
Adding streamer to remove extra spaces from output

### PR DESCRIPTION
**Pull request by quic-amitraj**
Updated "cloud_ai_100_exec_kv" API with "TextStreamer" to remove extra space from output.

### CODE REVIEW

**Comment by ochougul** [comment]
Is this tested? Can you please provide one example output using infer API?

**Comment by quic-amitraj** [comment]
> Is this tested? Can you please provide one example output using infer API?

Before -

image

After-

image

CI also passed for the same.

**Comment by quic-amitraj** [comment]
After adding streamer, noticed notable downgrade in performance. 

image

**Comment by ochougul** [comment]
Closing this PR for now. as the issue won't be fixed here.

**Pull request closed without merging**
