### PR TITLE
Fix head dimension in mistral

### PR DESCRIPTION
**Pull request by quic-mamta**
Fix head dimension in mistral

### CODE REVIEW

**Comment by quic-akuruvil** [comment]
Hi @quic-mamta, 2layer testing of all the other supported models was verified?

**Comment by quic-mamta** [comment]
> Hi @quic-mamta, 2layer testing of all the other supported models was verified?

CI is passing on this for 2 layer phi3 model and 1 layer other models.

**Review by quic-akuruvil — COMMENTED** [review]
LGTM

**Review by quic-rishinr — APPROVED** [review]

**Comment by quic-rishinr** [comment]
Looks good to me. Merging the PR

**Pull request merged**
