### PR TITLE
renamed exec APIs

### PR DESCRIPTION
**Pull request by ochougul**
* renamed `latency_kv_stats` API to 'exec'

### CODE REVIEW

**Review by vbaddi — APPROVED** [review]

**Comment by vbaddi** [comment]
LGTM, please resolve the conflicts and merge it.

**Comment by anujgupt-github** [comment]
Please resolve conflicts, and then good to go

**Comment by ochougul** [comment]
Resolved conflicts.

**Review by vbaddi — APPROVED** [review]
LGTM.

**Pull request merged**
