### PR TITLE
Added support for Mixtral architecture

### PR DESCRIPTION
**Pull request by quic-rishinr**

### CODE REVIEW

**Review by anujgupt-github — CHANGES_REQUESTED** [review]
This PR should only include Mixtral modeling changes.

**Comment by vbaddi** [comment]
CI is failing, fixed here #62

**Review by anujgupt-github — APPROVED** [review]

**Review by vbaddi — APPROVED** [review]
Changes LGTM. @quic-rishinr post the merge pls review #62 and get it to closure to enable CI pipeline for release branch

**Comment by quic-rishinr** [comment]
Anuj other changes are just code clean ups. 
Sure Vinayak.

**Pull request merged**
