### PR TITLE
mpt fix for continous batching

### PR DESCRIPTION
**Pull request by quic-mamta**
mpt fix for continous batching

### CODE REVIEW

**Comment by anujgupt-github** [comment]
Please raise a PR for mainline too

**Comment by quic-mamta** [comment]
> Please raise a PR for mainline too

Ilango has added these changes in PR 116

**Review by ochougul — APPROVED** [review]
this LGTM.
Are you going to add anything else here?

**Comment by quic-rishinr** [comment]
> Please raise a PR for mainline too

@anujgupt-github since we are planning to support CB by default going forward, I think we should remove this check from mainline.

**Pull request merged**
